# Generated by Django 3.0.2 on 2020-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200401_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('magt_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
